python: can't open file '/tmp/gptme-evals-yh25ljhj/prime.py': [Errno 2] No such file or directory
