python: can't open file '/tmp/gptme-evals-ryy54nke/hello.py': [Errno 2] No such file or directory
