python: can't open file '/tmp/gptme-evals-ayck86ga/hello.py': [Errno 2] No such file or directory
