python: can't open file '/tmp/gptme-evals-jfls17s2/hello.py': [Errno 2] No such file or directory
