python: can't open file '/tmp/gptme-evals-hy_g22pq/hello.py': [Errno 2] No such file or directory
